use_frameworks!

platform :ios, '9.0'

target 'LoadingView_NHT_Example' do
  pod 'LoadingView_NHT', :path => '../'

  target 'LoadingView_NHT_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
